title: Kristin Hargrove # your name (or website title) here
logo: "/images/kh_image.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Full stack developer with experience in both the mortgage and technology industry. 
  <br><br>
  Coachable full stack software developer with an eagerness for a new opportunity to lear and grow.<br /> Encouraging and collaborative teammate who enjoys listening and learning from others, but also exploring and finding answers independently. 
  <br><br>
  <a href="http://linkedin.com/in/kristin-hargrove">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-9MMJXHP8ZZ # your Google Analytics tracking ID here
